name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          $version = '${{ github.event.release.tag_name }}'.TrimStart('v')
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Pack
        run: nuget pack MMAPI.nuspec -Version ${{ steps.version.outputs.version }}

      - name: Push
        run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }} -SkipDuplicate
